django_pjt5/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<username>/follow', views.follow, name='follow'),
    path('<username>/profile_picture_update', views.profile_picture_update, name='profile_picture_update'),
    ]

django_pjt5/django_pjt5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('', views.index)
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_pjt5/movies/urls.py
from django.urls import path, include
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/', views.detail_movie, name='detail_movie'),
    path('<int:movie_id>/like/', views.like, name='like')
]

django_pjt5/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from movies.models import *

# Create your models here.
class User(AbstractUser):
    profile_picture = models.ImageField(blank=True)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'followings')
    like_movies = models.ManyToManyField(Movie, related_name = 'users_like_movie')
    like_genres = models.ManyToManyField(Genre, related_name = 'users_like_genre')

django_pjt5/movies/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField(max_length=30)


class Movie(models.Model):
    title = models.CharField(max_length=300)
    original_title = models.CharField(max_length=300)
    release_date = models.DateField()
    popularity = models.FloatField()
    vote_count = models.IntegerField()
    vote_average = models.FloatField()
    adult = models.BooleanField()
    overview = models.TextField()
    original_language = models.CharField(max_length=10)
    poster_path = models.CharField(max_length=100)
    backdrop_path = models.CharField(max_length=100, default='')
    genres = models.ManyToManyField(Genre, related_name='movies')

django_pjt5/accounts/forms.py
from . import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username','first_name','last_name','email','profile_picture', 'like_genres']

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['profile_picture']

django_pjt5/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm, UpdateProfileForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate

# Create your views here.
def index(request):
    return render (request,'accounts/index.html')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST,request.FILES)
        if form.is_valid():
            new_user=form.save()
            authenticated_user=authenticate(username=new_user.username,password=request.POST['password1'])
            auth_login(request,authenticated_user)
            return redirect('accounts:profile', authenticated_user.username)
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request,'accounts/form.html',context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            auth_login(request,form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request,'accounts/form.html',context)


def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@login_required
def profile(request,username):
    User = get_user_model()
    profile_user = User.objects.get(username=username)
    if len(str(profile_user.profile_picture)) == 0:
        profile_user.profile_picture = 'default_image.png'
        profile_user.save()
    context = {
        'profile_user' : profile_user,
    }

    return render(request,'accounts/profile.html',context)

@login_required
def follow(request,username):
    User = get_user_model()
    me = request.user
    you = User.objects.get(username=username)

    if me in you.followers.all():
        you.followers.remove(me)
    else:
        you.followers.add(me)

    return redirect('accounts:profile', username)

def profile_picture_update(request,username):
    user=get_object_or_404(get_user_model() ,username=username)
    if request.method == 'POST':
        form = UpdateProfileForm(request.POST,request.FILES)
        if form.is_valid():
            # user.profile_picture = form.profile_picture
            # user.save()
            new_user = form.save(commit=False)
            user.profile_picture = new_user.profile_picture
            user.save()
            return redirect('accounts:profile',username)
    else:
        form = UpdateProfileForm(instance=user)

    context = {
        'form':form
    }
    return render(request,'accounts/form.html',context)

django_pjt5/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Genre
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from django.http import JsonResponse
from django.core.paginator import Paginator
import random

# Create your views here.
def index(request):
    movies = Movie.objects.all()

    # paginator
    paginator = Paginator(movies, 5)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # 추천
    genres = Genre.objects.values('name')
    # 유저가 좋아하는 장르에서 우선뽑기(만약 좋아하는 장르가 여러개라면 //n개 뽑기)
    # 유저가 좋아하는 장르가 없다면?
    # 영화 랜덤추천
    like_genres = request.user.like_genres
    recomandedMovies = []
    id_arr = []
    for movie in movies:
        id_arr.append(movie.id)
    id_set = random.sample(id_arr, 10)
    for id_ in id_arr:
        recomandedMovies.append(Movie.objects.get(id=id_))

    context = {
        'movies' : movies,
        'page_obj' : page_obj,
        'recomandedMovies' :recomandedMovies,
    }
    return render(request, 'movies/index.html', context)

def detail_movie(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail_movie.html', context)

# @login_required
def like(request, movie_id):
    user = request.user 
    movie = get_object_or_404(Movie, pk=movie_id)
    
    if movie.users_like_movie.filter(pk=user.pk).exists():
        movie.users_like_movie.remove(user)
        status = False
    else:
        movie.users_like_movie.add(user)
        status = True

    context = {
        'status': status,
        'count': movie.users_like_movie.count(),
    }

    return JsonResponse(context)

django_pjt5/accounts/templates/accounts/form.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
        <form action = '' method ='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button "제출" button_type="submit" button_class="btn-primary" %}
    </form>
            {% bootstrap_javascript jquery='full' %}
        {% bootstrap_css %}
    </body>
</html>

django_pjt5/accounts/templates/accounts/index.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
    <h1>{{user.username}}님 하이요!</h1>
    {% endif %}

    <a href='{% url 'accounts:signup' %}'>signup</a>
    <a href='{% url 'accounts:logout' %}'>logout</a>
    <a href='{% url 'accounts:login' %}'>login</a>
    <div class="container">
    {% block body %}
    {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_css %}
</body>
</html>

django_pjt5/accounts/templates/accounts/profile.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% if request.user == profile_user %}
        <a href='{% url 'accounts:profile_picture_update' profile_user.username %}'><img src="{{ profile_user.profile_picture.url }}" class="w-25 rounded-circle"></a>
    {% else %}
        <img src="{{ profile_user.profile_picture.url }}" class="w-25 rounded-circle">
    {% endif %}

    <h1>{{profile_user.username}}님의 Profile</h1>
    <h1><a>{{profile_user.followers.all|length}}명</a>이 팔로우 합니다.</h1>
    {% if user.is_authenticated %}
        {% if user != profile_user %}
            {% if user in profile_user.followers.all %}
                <a href='{% url 'accounts:follow' profile_user.username %}'>팔로우 취소</a>
            {% else %}
                <a href='{% url 'accounts:follow' profile_user.username %}'>팔로우</a>
            {% endif %}
        {% endif %}
    {% endif %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_css %}
</body>
</html>

django_pjt5/movies/templates/movies/detail_movie.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <div class="w-75 m-auto">
        <img src="{{ movie.id }}" alt="" class="d-block w-100">
        <h1 class="text-center mt-3">{{movie.title}}</h1>
        <hr>
        <p>{{movie.summary}}</p>
        {% for review in movie.reviews.all %}
            <hr>
            <a href="#" class="h5 text-secondary d-inline">
            <p class="">
                
            </p></a>
        {% endfor %}
        <br><br>
        <a href="#" type="button" class="btn btn-primary">리뷰 쓰기</a>
    </div>



{% endblock %}

django_pjt5/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load bootstrap_pagination %}

{% block body %}

<h1 class="text-center m-4"> 추천 영화 </h1>
<!-- carousel _ 추천 영화 보여주기  -->
<div id="carouselExampleFade" class="carousel slide carousel-fade w-50 m-auto" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>

  <div class="carousel-inner" style="height:450px;">
    {% for movie in recomandedMovies %}
        <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
          <a href="{% url 'movies:detail_movie' movie.id %}"><img src="https://image.tmdb.org/t/p/w780/{{movie.poster_path}}" style="" class="d-block w-100" alt="..."></a>
        </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<hr>
<!-- 영화 데이터 _card layout  -->
<h1 class="text-center m-4"> Movie List</h1>
<div class="card-deck">
  {% for movie in page_obj %}
  <div class="card m-3">
    <img src="https://image.tmdb.org/t/p/w780/{{movie.poster_path}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{ movie.title }}</h5>
      <!-- <p class="card-text">무슨내용을 쓸까나..</p> -->
      <hr>
    </div>
      <p class="m-3">
          {% if user in movie.users_like_movie.all %}
            <i class="fas fa-heart fa-lg" style="color:crimson" data-id="{{ movie.id }}"></i>
          {% else %}
            <i class="fas fa-heart fa-lg" style="color:black" data-id="{{ movie.id }}"></i>
          {% endif %}
      </p>
      <p>
        <span><span id="like-count-{{ movie.id }}">{{ movie.users_like_movie.all|length }}</span> 명이 이 글을 좋아합니다.</span>
      </p>
    <div class="card-footer">
      <small class="text-muted">{{ movie.release_date }}</small>
    </div>
  </div>
  {% endfor %}
</div>



<!-- pagination -->
{% bootstrap_paginate page_obj range=10 show_prev_next="false" show_first_last="true" %}

<div class="pagination m-3 justify-content-center">
  <span class="step-links justify-content-center">
      {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current justify-content-center">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
  </span>
</div>

<!-- 좋아요 기능을 ajax로 처리하기 위해서 작성하는 js -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const heartBtns = document.querySelectorAll('i')

  heartBtns.forEach((heartBtns)=>{
    heartBtns.addEventListener('click', function(event){
      const movieId = event.target.dataset.id
      const countSpan = document.querySelector(`#like-count-${movieId}`)

      axios.get(`/movies/${movieId}/like/`)
      .then((response)=>{
        // console.log(response)
        if (response.data.status) {
          event.target.style.color = 'crimson'
          countSpan.innerHTML = response.data.count
        } else {
          event.target.style.color = 'black'
          countSpan.innerHTML = response.data.count
        }
      })
      .catch((error)=>{
        console.log(error)
      })
    })
  })
</script>
{% endblock %}
<a href="{% url 'movies:create_movie' %}" type="button" class="btn btn-primary mb-5"></a>

django_pjt5/templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <!-- font-awesome -->
    <script src="https://kit.fontawesome.com/1c45f569a6.js" crossorigin="anonymous"></script>
    <!-- axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        {% if user.is_authenticated %}
        {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href='{% url 'accounts:logout' %}'>logout</a>
          </li>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href='{% url 'accounts:signup' %}'>signup</a>
          </li>
          <li class="nav-item">
            <a href='{% url 'accounts:login' %}' class="nav-link" >login</a>
          </li>

        </ul>
        {% endif %}
      </div>
      <div>
          {% if user.is_authenticated %}
              <h5>{{user.username}}님 하이요!</h5>
          {% else %}
              <h5>login 해주세요</h5>
          {% endif %}
      </div>
    </nav>
    {% if user.is_authenticated %}
    {% endif %}

    <div class="container">
    {% block body %}
    {% endblock %}
    </div>
</body>

{% bootstrap_javascript jquery='full' %}
{% bootstrap_css %}
</html>